name: Pull Request Event

on:
  pull_request:
    types:
      - closed

jobs:
  execute:
    if: ${{ github.base_ref == 'merge_test' && github.event.pull_request.merged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Execution
        run: echo '実行されました'
